//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VnextOC.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class R {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal R() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VnextOC.Data.R", typeof(R).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;results&quot;: [
        ///        {
        ///            &quot;status&quot;: &quot;upcoming&quot;,
        ///            &quot;visibility&quot;: &quot;public&quot;,
        ///            &quot;maybe_rsvp_count&quot;: 0,
        ///            &quot;venue&quot;: {
        ///                &quot;id&quot;: 11835602,
        ///                &quot;zip&quot;: &quot;92660&quot;,
        ///                &quot;lon&quot;: -117.867828,
        ///                &quot;repinned&quot;: false,
        ///                &quot;name&quot;: &quot;TEKsystems&quot;,
        ///                &quot;state&quot;: &quot;CA&quot;,
        ///                &quot;address_1&quot;: &quot;100 Bayview Circle #3400&quot;,
        ///                &quot;lat&quot;: 33.655819,
        ///                &quot;city&quot;: &quot;Newport Beach&quot;,
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fakeData {
            get {
                return ResourceManager.GetString("fakeData", resourceCulture);
            }
        }
    }
}
